#!/bin/bash

# trap ctrl-c and call ctrl_c()

case "$1" in
	deploy )
		rsync -rtvz * scia:/www/scia -C --delete --exclude "node_modules/"
		exit $?
		;;
	dbsync )
		sudo mongod &
		mongodPID=$!
		sleep 2s
		mongo < .dbsync.js
		mongo < .dbconfig.js
		sudo kill $mongodPID
		;;
	run )
		sudo mongod &		
		sleep 2s
		node server.js
		;;
esac