#!/bin/bash

# trap ctrl-c and call ctrl_c()


function dbsync {
	sudo mongod &
	mongodPID=$!
	sleep 2s
	mongo < .dbsync.js
	mongo < .dbconfig.js
	sudo kill $mongodPID
}


# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root"
   exit 1
fi

case "$1" in
	dbsync )
		dbsync
		;;
	deploy )
		rsync -rtvz * scia:/www/scia -C --delete --exclude "node_modules/"
		exit $?
		;;
	run )
		sudo mongod &		
		sleep 2s
		node server.js
		;;
	test )
		dbsync
		make test
		;;
esac